# Generated by Django 6.0.1 on 2026-01-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_problem_difficulty_alter_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
