# Generated by Django 6.0.1 on 2026-02-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_problem_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='failed_expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='failed_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='failed_user_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
